version: '3.9'

services:
  db:
    container_name: hotel-booking-db
    image: mysql
    volumes:
      - hotel-booking-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'hotel-booking'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    healthcheck:
      test: 'mysqladmin ping --silent'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  hotel-booking-data:
